name: Second Workflow
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Gets code
        uses: actions/checkout@v4.2.2
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
    # Version Spec of the version to use in SemVer notation.
    # It also admits such aliases as lts/*, latest, nightly and canary builds
    # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
          node-version: 18
          
      - name: Install dependencies
        run: |
          cd "02 Starting Project"
          npm ci  # Ensures vitest and other dependencies are installed
          
      - name: testing code
        run: |
          cd "02 Starting Project"

          npm test

  deploy:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Gets code
        uses: actions/checkout@v4.2.2
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
    # Version Spec of the version to use in SemVer notation.
    # It also admits such aliases as lts/*, latest, nightly and canary builds
    # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
          node-version: 18
          
      - name: Install dependencies
        run: |
          cd "02 Starting Project"
          npm ci  # Ensures vitest and other dependencies are installed
      - name: running code
        run: |
          cd "02 Starting Project"
          npm run build
